<?php

return [
    "APP_NAME" => env("APP_NAME"),
    "APP_LABEL" => env("APP_LABEL"),
    "APP_ICON" => env("APP_ICON"),
    "APP_LOGO" => env("APP_LOGO"),
    "APP_ENV" => env("APP_ENV"),
    "APP_KEY" => env("APP_KEY"),
    "APP_DEBUG" => env("APP_DEBUG"),
    "APP_URL" => env("APP_URL"),
    "IS_BP" => env("IS_BP"),
    "COMPANY_NAME" => env("COMPANY_NAME", "PT. Samaya Karina Abadi"),
    "COLOR_PRIMARY" => env("COLOR_PRIMARY"),
    "COLOR_ACCENT" => env("COLOR_ACCENT"),
    "LOCALE" => env("LOCALE"),
    "ENABLE_CAM" => env("ENABLE_CAM"),
    "ASSET_DIR" => env("ASSET_DIR"),
    "ASSET_URL" => env("ASSET_URL"),
    "PORTAL_HOST" => env("PORTAL_HOST"),
    "APPLICANT_HOST" => env("APPLICANT_HOST"),
    "EMPLOYER_HOST" => env("EMPLOYER_HOST"),
    "IS_PORTAL" => env("IS_PORTAL"),
    "PORTAL_STATE" => env("PORTAL_STATE"),
    "MAIL_FROM_ADDRESS" => env("MAIL_FROM_ADDRESS"),
    "REGISTER_URL" => env("REGISTER_URL"),
    "WA_NO" => env("WA_NO"),
    "ID_MASTER" => env("ID_MASTER"),
    "SSO_BROKER_NAME" => env("SSO_BROKER_NAME"),
    "FIREBASE_API_KEY" => "AAAApbaJfcM:APA91bGBtikikpftShJLJQ6WiwowtqWmR5BdKKzrgUzwh-8CBvgrcSgWYsFMcgdcPWH2ocKnmaRmktz3K84ZeyLFPZCvFjNCgNMNz13d_TOesVsoSrpxjndG7asCtX87W7tEROvPwTDh",
    "CRM_ADMIN_MODULES" => ["user" => 'Manage user', "team" => "Manage team", "preferences" => "Manage properties such as pipeline, stage, custom and custom field.", "products" => "Manage products", "dashboard_access" => 'View Report dashboard access'],
    "CRM_ADMIN_ACTION" => ["add", "edit", "archieve"],
    // "CRM_USER_MODULES" => ["contact_access", "company_access", "opportunity_access"],
    "CRM_USER_MODULES" => ["owner", "collaborator"],
    // "CRM_USER_ACTION" => ["view", "edit", "search_association", "delete", "upload", "download"],
    "CRM_USER_ACTION" => ["view"],
    "CRM_USER_PERMISSION" => ["1" => "everything", "2" => "team_only", "3" => "owned_only"],
    "CRM_PROPERTIES_TYPE" => ["1" => "Text (Up to 100 characters)", "Text description (Longer than 100 characters)", "Dropdown select", "Single select", "Multiple select", "Auto complete (Up to 100 character show suggestion from input)", "Opportunity (Add new or suggestion from your opportunity)", "Colaborator (Add new or suggestion from your company)", "Company (Add new or suggestion from company list)", "Contact (Add new or suggestion from contact list)", "Product (Suggestion from product list)", "Scale", "Numerical", "Monetary", "Phone number", "Email", "Time", "Time range", "Date", "Date range", "Address", "Attachment", "URL"],
    "EXPORT_COLUMNS_APPLICANT" => [
        "name" => "Nama Lengkap",
        "birth_date" => "Tanggal Lahir",
        "email" => "Email",
        "religion" => "Agama",
        "gender" => "Jenis Kelamin",
        "phone" => "Nomor Telepon",
        "married" => "Status Pernikahan",
        "province" => "Provinsi",
        "city" => "Kota",
        "address" => "Alamat",
        "exp" => "Pengalaman Kerja",
        "edu" => "Pendidikan",
        "salary" => "Gaji yang diharapkan",
        "website" => "Website",
        "behance" => "Behance",
        "dribble" => "Dribble",
        "github" => "Github",
        "mobile" => "Mobile",
        "other_link" => "Link Lain",
        "test_result" => ["1", "2", "9", "13", "16", "17"]
    ],
    "DASHBOARD_CRM" => [
        "TOTAL_OPPORTUNITY" => 1,
        "CONVERSION_RATE" => 1,
        "OPPORTUNITY_WIN_RATE" => 1,
        "OPPORTUNITY_LOSE_RATE" => 1,
        "SALES_CYCLE" => 1,
        "ESTIMATE_REVENUE" => 1,
        "OPPORTUNITY_PERFORMANCE" => 1,
        "SALES_CYCLE_CHART" => 1,
        "SALES_WIN_RATE" => 1,
        "TOP_3_COMPANY" => 1,
        "TOP_3_PRODUCT" => 1,
        "OPPORTUNITY_WORTH" => 1,
        "OPPORTUNITY_WIN" => 1,
        "OPPORTUNITY_LOSE" => 1,
    ],
    "COLOR_PALLET" => [
        "#FFC119",
        // "#FFE6A3",
        // "#FCD9C4",
        "#D26222",
        "#DD3545",
        "#E45D6A",
        // "#F1AEB5",
        // "#F5C2C7",
        "#3F1F85",
        "#5837FF",
        "#8F66EA",
        // "#E1D7FA",
        "#28A845",
        "#7ECB8F",
        // "#BFE5C7",
        // "#EBEBEB",
        "#000",
        "#4B5675",
        "#ff1493"
    ],
    "ATTENDANCE_DASHBOARD_WIDGET" => [
        "reason_trend" => [
            "label" => "Tren Kehadiran",
            "descriptions" => "Menampilkan data bulanan reason terpilih berdasarkan departement/division",
            "images" => "reason_trend.png"
        ],
        "overtime_trend" => [
            "label" => "Tren Lembur",
            "descriptions" => "Menampilkan data bulanan overtime berdasarkan departement/division",
            "images" => "overtime_trend.png"
        ],
        "overtime_hours" => [
            "label" => "Jam Lembur",
            "descriptions" => "<div class='d-flex flex-column align-items-center'><span>Total Jam Lembur (7 hari)</span><div class='border border-dark my-3 opacity-50 w-100'></div><span>Total Employee yang lembur (7 hari)</span></div>",
            "images" => "overtime_hours.png"
        ],
        "absence_rate" => [
            "label" => "Rata-rata Kehadiran",
            "descriptions" => "<div class='d-flex align-items-center'><div class='d-flex flex-column align-items-center'><span>Total Days Absent</span><div class='border border-dark my-3 opacity-50 w-100'></div><span>Total Scheduled Working Days</span></div><span class='mx-3'>X</span><span>100%</span></div>",
            "images" => "absence_rate.png"
        ],
        "location_attendance" => [
            "label" => "Lokasi Kehadiran",
            "descriptions" => "Menampilkan Type kehadiran Employee berdasarkan lokasi",
            "images" => "location_attendance.png"
        ],
    ],
    'uac_permissions' => [
        "personel" => [
            "employee",
            "employee_transfer",
            "employee_offences",
            "employee_terminate/resign",
            "onboarding",
            'request',
            "personel_setting",
        ],
        "attendance" => [
            "schedule",
            "registrations",
            "correction",
            "overtime",
            "leave",
            "approval",
            "collect_data",
            "attendance_setting"
        ],
        "payroll" => [
            "payroll"
        ],
        "crm" => [
            "opportunity",
            "list_contact",
            "list_company",
            "list_file",
            "archive",
            "products",
            "crm_setting"
        ],
        "lms" => [
            "lms",
            'author'
        ],
        "ess" => [
            "ess",
        ],
        "company_setting" => [
            "user_access_control",
            "company_list",
        ],
        "recruitment" => [
            "search_applicant",
            "job_ads",
            "calendar"
        ]
    ],
    'uac_actions' => ["view", "add", "edit", "delete"],
    'overtime_type' => [
        "in" => "Overtime In",
        "out" => "Overtime Out",
        "off_hol" => "Overtime Holiday",
        "off_day" => "Overtime Day Off",
    ],
    'reason_operator' => [
        "<>" => "<>",
        ">" => ">",
        "<" => "<",
        ">=" => ">=",
        "<=" => "<=",
        "==" => "="
    ],
    'tax_type' => [
        1=> "local", "foreign"
    ],
    'payment_method' => [
        1=> "cash", "transfer", "both"
    ],
    "payment_schedule" => [
        1=> "monthly", "daily", "two weekly", 'half a month'
    ],
    "zone_type" => [1,2,3,4,5,6,7,8],
    "promo_src" => [
        "biaya_kirim" => "Biaya Kirim",
        "pickup_amount" => "Biaya Pickup",
    ],
    "currency"=> [
        "AED"=> "United Arab Emirates dirham",
        "AFN"=> "Afghan afghani",
        "ALL"=> "Albanian lek",
        "AMD"=> "Armenian dram",
        "ANG"=> "Netherlands Antillean guilder",
        "AOA"=> "Angolan kwanza",
        "ARS"=> "Argentine peso",
        "AUD"=> "Australian dollar",
        "AWG"=> "Aruban florin",
        "AZN"=> "Azerbaijani manat",
        "BAM"=> "Bosnia and Herzegovina convertible mark",
        "BBD"=> "Barbados dollar",
        "BDT"=> "Bangladeshi taka",
        "BGN"=> "Bulgarian lev",
        "BHD"=> "Bahraini dinar",
        "BIF"=> "Burundian franc",
        "BMD"=> "Bermudian dollar",
        "BND"=> "Brunei dollar",
        "BOB"=> "Boliviano",
        "BRL"=> "Brazilian real",
        "BSD"=> "Bahamian dollar",
        "BTN"=> "Bhutanese ngultrum",
        "BWP"=> "Botswana pula",
        "BYN"=> "New Belarusian ruble",
        "BYR"=> "Belarusian ruble",
        "BZD"=> "Belize dollar",
        "CAD"=> "Canadian dollar",
        "CDF"=> "Congolese franc",
        "CHF"=> "Swiss franc",
        "CLF"=> "Unidad de Fomento",
        "CLP"=> "Chilean peso",
        "CNY"=> "Renminbi|Chinese yuan",
        "COP"=> "Colombian peso",
        "CRC"=> "Costa Rican colon",
        "CUC"=> "Cuban convertible peso",
        "CUP"=> "Cuban peso",
        "CVE"=> "Cape Verde escudo",
        "CZK"=> "Czech koruna",
        "DJF"=> "Djiboutian franc",
        "DKK"=> "Danish krone",
        "DOP"=> "Dominican peso",
        "DZD"=> "Algerian dinar",
        "EGP"=> "Egyptian pound",
        "ERN"=> "Eritrean nakfa",
        "ETB"=> "Ethiopian birr",
        "EUR"=> "Euro",
        "FJD"=> "Fiji dollar",
        "FKP"=> "Falkland Islands pound",
        "GBP"=> "Pound sterling",
        "GEL"=> "Georgian lari",
        "GHS"=> "Ghanaian cedi",
        "GIP"=> "Gibraltar pound",
        "GMD"=> "Gambian dalasi",
        "GNF"=> "Guinean franc",
        "GTQ"=> "Guatemalan quetzal",
        "GYD"=> "Guyanese dollar",
        "HKD"=> "Hong Kong dollar",
        "HNL"=> "Honduran lempira",
        "HRK"=> "Croatian kuna",
        "HTG"=> "Haitian gourde",
        "HUF"=> "Hungarian forint",
        "IDR"=> "Indonesian rupiah",
        "ILS"=> "Israeli new shekel",
        "INR"=> "Indian rupee",
        "IQD"=> "Iraqi dinar",
        "IRR"=> "Iranian rial",
        "ISK"=> "Icelandic króna",
        "JMD"=> "Jamaican dollar",
        "JOD"=> "Jordanian dinar",
        "JPY"=> "Japanese yen",
        "KES"=> "Kenyan shilling",
        "KGS"=> "Kyrgyzstani som",
        "KHR"=> "Cambodian riel",
        "KMF"=> "Comoro franc",
        "KPW"=> "North Korean won",
        "KRW"=> "South Korean won",
        "KWD"=> "Kuwaiti dinar",
        "KYD"=> "Cayman Islands dollar",
        "KZT"=> "Kazakhstani tenge",
        "LAK"=> "Lao kip",
        "LBP"=> "Lebanese pound",
        "LKR"=> "Sri Lankan rupee",
        "LRD"=> "Liberian dollar",
        "LSL"=> "Lesotho loti",
        "LYD"=> "Libyan dinar",
        "MAD"=> "Moroccan dirham",
        "MDL"=> "Moldovan leu",
        "MGA"=> "Malagasy ariary",
        "MKD"=> "Macedonian denar",
        "MMK"=> "Myanmar kyat",
        "MNT"=> "Mongolian tögrög",
        "MOP"=> "Macanese pataca",
        "MRO"=> "Mauritanian ouguiya",
        "MUR"=> "Mauritian rupee",
        "MVR"=> "Maldivian rufiyaa",
        "MWK"=> "Malawian kwacha",
        "MXN"=> "Mexican peso",
        "MXV"=> "Mexican Unidad de Inversion",
        "MYR"=> "Malaysian ringgit",
        "MZN"=> "Mozambican metical",
        "NAD"=> "Namibian dollar",
        "NGN"=> "Nigerian naira",
        "NIO"=> "Nicaraguan córdoba",
        "NOK"=> "Norwegian krone",
        "NPR"=> "Nepalese rupee",
        "NZD"=> "New Zealand dollar",
        "OMR"=> "Omani rial",
        "PAB"=> "Panamanian balboa",
        "PEN"=> "Peruvian Sol",
        "PGK"=> "Papua New Guinean kina",
        "PHP"=> "Philippine peso",
        "PKR"=> "Pakistani rupee",
        "PLN"=> "Polish złoty",
        "PYG"=> "Paraguayan guaraní",
        "QAR"=> "Qatari riyal",
        "RON"=> "Romanian leu",
        "RSD"=> "Serbian dinar",
        "RUB"=> "Russian ruble",
        "RWF"=> "Rwandan franc",
        "SAR"=> "Saudi riyal",
        "SBD"=> "Solomon Islands dollar",
        "SCR"=> "Seychelles rupee",
        "SDG"=> "Sudanese pound",
        "SEK"=> "Swedish krona",
        "SGD"=> "Singapore dollar",
        "SHP"=> "Saint Helena pound",
        "SLL"=> "Sierra Leonean leone",
        "SOS"=> "Somali shilling",
        "SRD"=> "Surinamese dollar",
        "SSP"=> "South Sudanese pound",
        "STD"=> "São Tomé and Príncipe dobra",
        "SVC"=> "Salvadoran colón",
        "SYP"=> "Syrian pound",
        "SZL"=> "Swazi lilangeni",
        "THB"=> "Thai baht",
        "TJS"=> "Tajikistani somoni",
        "TMT"=> "Turkmenistani manat",
        "TND"=> "Tunisian dinar",
        "TOP"=> "Tongan paʻanga",
        "TRY"=> "Turkish lira",
        "TTD"=> "Trinidad and Tobago dollar",
        "TWD"=> "New Taiwan dollar",
        "TZS"=> "Tanzanian shilling",
        "UAH"=> "Ukrainian hryvnia",
        "UGX"=> "Ugandan shilling",
        "USD"=> "United States dollar",
        "UYI"=> "Uruguay Peso en Unidades Indexadas",
        "UYU"=> "Uruguayan peso",
        "UZS"=> "Uzbekistan som",
        "VEF"=> "Venezuelan bolívar",
        "VND"=> "Vietnamese đồng",
        "VUV"=> "Vanuatu vatu",
        "WST"=> "Samoan tala",
        "XAF"=> "Central African CFA franc",
        "XCD"=> "East Caribbean dollar",
        "XOF"=> "West African CFA franc",
        "XPF"=> "CFP franc",
        "XXX"=> "No currency",
        "YER"=> "Yemeni rial",
        "ZAR"=> "South African rand",
        "ZMW"=> "Zambian kwacha",
        "ZWL"=> "Zimbabwean dollar"
    ],
    'document_weight' => [0.5, 1, 1.5, 2],
    'limit' => [
        "berat" => 300,
        'panjang' => 300,
        'tinggi' => 160,
        'lebar' => 200
    ]
];
